#!/usr/bin/env python3
"""Generate typed Python modules and documentation from schemas/ontology.yaml.

Usage:
    python scripts/generate_from_ontology.py          # generate files
    python scripts/generate_from_ontology.py --check   # verify files are up-to-date
"""

from __future__ import annotations

import argparse
import difflib
import sys
import textwrap
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
ONTOLOGY_PATH = ROOT / "schemas" / "ontology.yaml"
TYPES_PATH = ROOT / "cmis_v2" / "generated" / "types.py"
VALIDATORS_PATH = ROOT / "cmis_v2" / "generated" / "validators.py"
DOCS_PATH = ROOT / "docs" / "ontology-map.md"

HEADER = (
    '# Auto-generated from schemas/ontology.yaml by scripts/generate_from_ontology.py\n'
    '# DO NOT EDIT THIS FILE DIRECTLY. Regenerate with:\n'
    '#   python scripts/generate_from_ontology.py\n'
)


def load_ontology() -> dict[str, Any]:
    """Load and return the ontology dict from YAML."""
    with open(ONTOLOGY_PATH, encoding="utf-8") as f:
        raw: dict[str, Any] = yaml.safe_load(f)
    ont: dict[str, Any] = raw["ontology"]
    return ont


# ---------------------------------------------------------------------------
# types.py generation
# ---------------------------------------------------------------------------

def _generate_types(ont: dict[str, Any]) -> str:
    """Return the full source of cmis_v2/generated/types.py."""
    lines: list[str] = []
    lines.append(HEADER)
    lines.append("from __future__ import annotations\n")
    lines.append("from typing import Any, Literal\n")
    lines.append("from pydantic import BaseModel, field_validator\n")
    lines.append("")

    # -- ONTOLOGY_VERSION --
    version = ont.get("version", "0.0.0")
    lines.append(f'ONTOLOGY_VERSION: str = "{version}"')
    lines.append("")

    # -- NodeType Literal --
    node_names = list(ont["node_types"].keys())
    node_literal = ", ".join(f'"{n}"' for n in node_names)
    lines.append(f"NodeType = Literal[{node_literal}]")
    lines.append("")

    # -- EdgeType Literal --
    edge_names = list(ont["edge_types"].keys())
    edge_literal = ", ".join(f'"{e}"' for e in edge_names)
    lines.append(f"EdgeType = Literal[{edge_literal}]")
    lines.append("")

    # -- Trait enum Literals --
    for trait_name, trait_def in ont["trait_definitions"].items():
        if trait_def["type"] == "enum":
            values = trait_def["values"]
            val_literal = ", ".join(f'"{v}"' for v in values)
            type_alias = "".join(part.capitalize() for part in trait_name.split("_")) + "Trait"
            lines.append(f"{type_alias} = Literal[{val_literal}]")
    lines.append("")

    # -- MetricId Literal --
    metric_ids = list(ont["metrics"].keys())
    metric_literal = ", ".join(f'"{m}"' for m in metric_ids)
    lines.append(f"MetricId = Literal[{metric_literal}]")
    lines.append("")

    # -- PolicyMode Literal --
    modes = ont["policy_schema"]["modes"]
    mode_literal = ", ".join(f'"{m}"' for m in modes)
    lines.append(f"PolicyMode = Literal[{mode_literal}]")
    lines.append("")

    # -- WorkflowId Literal --
    workflows = ont["workflow_schema"]["canonical_workflows"]
    wf_literal = ", ".join(f'"{w}"' for w in workflows)
    lines.append(f"WorkflowId = Literal[{wf_literal}]")
    lines.append("")

    # -- Per-node REQUIRED_TRAITS / OPTIONAL_TRAITS --
    lines.append("# Per-node-type trait sets")
    for ntype, ndef in ont["node_types"].items():
        upper = ntype.upper()
        req = ndef.get("required_traits", [])
        opt = ndef.get("optional_traits", [])
        req_str = ", ".join(f'"{t}"' for t in req)
        opt_str = ", ".join(f'"{t}"' for t in opt)
        lines.append(f'{upper}_REQUIRED_TRAITS: frozenset[str] = frozenset({{{req_str}}})')
        lines.append(f'{upper}_OPTIONAL_TRAITS: frozenset[str] = frozenset({{{opt_str}}})')
    lines.append("")

    # -- _REQUIRED_TRAITS / _ALL_TRAITS dicts --
    lines.append("_REQUIRED_TRAITS: dict[str, frozenset[str]] = {")
    for ntype in ont["node_types"]:
        upper = ntype.upper()
        lines.append(f'    "{ntype}": {upper}_REQUIRED_TRAITS,')
    lines.append("}")
    lines.append("")

    lines.append("_ALL_TRAITS: dict[str, frozenset[str]] = {")
    for ntype in ont["node_types"]:
        upper = ntype.upper()
        lines.append(f'    "{ntype}": {upper}_REQUIRED_TRAITS | {upper}_OPTIONAL_TRAITS,')
    lines.append("}")
    lines.append("")

    # -- VALID_METRIC_IDS --
    valid_ids = ", ".join(f'"{m}"' for m in metric_ids)
    lines.append(f"VALID_METRIC_IDS: frozenset[str] = frozenset({{{valid_ids}}})")
    lines.append("")

    # -- METRIC_REGISTRY --
    # Standard fields are always included; all other fields pass through
    # automatically so that new ontology fields don't require codegen changes.
    _STANDARD_FIELDS = {"description", "unit", "aggregation"}
    lines.append("METRIC_REGISTRY: dict[str, dict[str, Any]] = {")
    for mid, mdef in ont["metrics"].items():
        entry_parts = [
            f'"description": "{mdef["description"]}"',
            f'"unit": "{mdef["unit"]}"',
            f'"aggregation": "{mdef["aggregation"]}"',
        ]
        for key, val in mdef.items():
            if key in _STANDARD_FIELDS:
                continue
            if isinstance(val, str):
                entry_parts.append(f'"{key}": "{val}"')
            else:
                entry_parts.append(f'"{key}": {val}')
        lines.append(f'    "{mid}": {{{", ".join(entry_parts)}}},')
    lines.append("}")
    lines.append("")

    # -- OntologyNode --
    lines.append("")
    lines.append("class OntologyNode(BaseModel):")
    lines.append('    """A node in the CMIS ontology graph."""')
    lines.append("")
    lines.append("    node_id: str")
    lines.append("    node_type: NodeType")
    lines.append("    traits: dict[str, Any] = {}")
    lines.append("")
    lines.append('    @field_validator("traits")')
    lines.append("    @classmethod")
    lines.append("    def check_required_traits(cls, v: dict[str, Any], info: Any) -> dict[str, Any]:")
    lines.append('        node_type: str | None = info.data.get("node_type")')
    lines.append("        if node_type is None:")
    lines.append("            return v")
    lines.append("        required = _REQUIRED_TRAITS.get(node_type, frozenset())")
    lines.append("        missing = required - set(v.keys())")
    lines.append("        if missing:")
    lines.append("            raise ValueError(")
    lines.append('                f"Node type {node_type!r} missing required traits: {sorted(missing)}"')
    lines.append("            )")
    lines.append("        return v")
    lines.append("")

    # -- OntologyEdge --
    lines.append("")
    lines.append("class OntologyEdge(BaseModel):")
    lines.append('    """An edge in the CMIS ontology graph."""')
    lines.append("")
    lines.append("    edge_id: str")
    lines.append("    edge_type: EdgeType")
    lines.append("    source_node_id: str")
    lines.append("    target_node_id: str")
    lines.append("    properties: dict[str, Any] = {}")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# validators.py generation
# ---------------------------------------------------------------------------

def _generate_validators(ont: dict[str, Any]) -> str:
    """Return the full source of cmis_v2/generated/validators.py."""
    lines: list[str] = []
    lines.append(HEADER)
    lines.append("from __future__ import annotations\n")
    lines.append("from typing import Any\n")
    lines.append("from cmis_v2.generated.types import (")
    lines.append("    VALID_METRIC_IDS,")
    lines.append("    _ALL_TRAITS,")
    lines.append("    _REQUIRED_TRAITS,")
    lines.append(")")
    lines.append("")
    lines.append("")

    # -- validate_metric_id --
    lines.append("def validate_metric_id(metric_id: str) -> bool:")
    lines.append('    """Return True if *metric_id* is a known metric."""')
    lines.append("    return metric_id in VALID_METRIC_IDS")
    lines.append("")
    lines.append("")

    # -- validate_node_traits --
    lines.append("def validate_node_traits(node_type: str, traits: dict[str, Any]) -> list[str]:")
    lines.append('    """Validate traits for a given node_type.')
    lines.append("")
    lines.append("    Returns a list of error strings (empty means valid).")
    lines.append('    """')
    lines.append("    errors: list[str] = []")
    lines.append("    required = _REQUIRED_TRAITS.get(node_type)")
    lines.append("    if required is None:")
    lines.append('        errors.append(f"Unknown node_type: {node_type!r}")')
    lines.append("        return errors")
    lines.append("    missing = required - set(traits.keys())")
    lines.append("    if missing:")
    lines.append('        errors.append(f"Missing required traits for {node_type!r}: {sorted(missing)}")')
    lines.append("    allowed = _ALL_TRAITS.get(node_type, frozenset())")
    lines.append("    unknown = set(traits.keys()) - allowed")
    lines.append("    if unknown:")
    lines.append('        errors.append(f"Unknown traits for {node_type!r}: {sorted(unknown)}")')
    lines.append("    return errors")
    lines.append("")
    lines.append("")

    # -- validate_pattern_spec --
    lines.append("def validate_pattern_spec(spec: dict[str, Any]) -> list[str]:")
    lines.append('    """Validate a pattern specification dict.')
    lines.append("")
    lines.append("    Checks trait_constraints and benchmark_metrics references.")
    lines.append("    Returns a list of error strings (empty means valid).")
    lines.append('    """')
    lines.append("    errors: list[str] = []")
    lines.append('    pattern_id: str = spec.get("pattern_id", "<unknown>")')
    lines.append("")
    lines.append("    # Validate trait_constraints reference valid node_types and traits")
    lines.append('    constraints = spec.get("trait_constraints", {})')
    lines.append("    for node_type, constraint in constraints.items():")
    lines.append("        all_traits = _ALL_TRAITS.get(node_type)")
    lines.append("        if all_traits is None:")
    lines.append("            # Allow node types not in ontology (e.g., resource, contract, event)")
    lines.append("            continue")
    lines.append('        for trait_name in constraint.get("required_traits", {}).keys():')
    lines.append("            if trait_name not in all_traits:")
    lines.append("                errors.append(")
    lines.append('                    f"[{pattern_id}] Trait {trait_name!r} not valid for '
                 'node_type {node_type!r}"')
    lines.append("                )")
    lines.append('        for trait_name in constraint.get("optional_traits", {}).keys():')
    lines.append("            if trait_name not in all_traits:")
    lines.append("                errors.append(")
    lines.append('                    f"[{pattern_id}] Trait {trait_name!r} not valid for '
                 'node_type {node_type!r}"')
    lines.append("                )")
    lines.append("")
    lines.append("    # Validate benchmark_metrics reference valid metric IDs")
    lines.append('    for met_id in spec.get("benchmark_metrics", []):')
    lines.append("        if not validate_metric_id(met_id):")
    lines.append("            errors.append(")
    lines.append('                f"[{pattern_id}] Unknown benchmark metric: {met_id!r}"')
    lines.append("            )")
    lines.append("")
    lines.append("    return errors")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# docs/ontology-map.md generation
# ---------------------------------------------------------------------------

def _generate_docs(ont: dict[str, Any]) -> str:
    """Return the full Markdown content for docs/ontology-map.md."""
    lines: list[str] = []
    lines.append("<!-- Auto-generated from schemas/ontology.yaml by scripts/generate_from_ontology.py -->")
    lines.append("<!-- DO NOT EDIT THIS FILE DIRECTLY. Regenerate with: -->")
    lines.append("<!--   python scripts/generate_from_ontology.py -->")
    lines.append("")
    lines.append(f"# CMIS v2 Ontology Map (v{ont['version']})")
    lines.append("")

    # Node Types
    lines.append("## Node Types")
    lines.append("")
    lines.append("| Name | Description | Required Traits | Optional Traits |")
    lines.append("|------|-------------|-----------------|-----------------|")
    for nname, ndef in ont["node_types"].items():
        req = ", ".join(ndef.get("required_traits", [])) or "-"
        opt = ", ".join(ndef.get("optional_traits", [])) or "-"
        lines.append(f"| `{nname}` | {ndef['description']} | {req} | {opt} |")
    lines.append("")

    # Edge Types
    lines.append("## Edge Types")
    lines.append("")
    lines.append("| Name | Description | Source | Target | Via |")
    lines.append("|------|-------------|--------|--------|-----|")
    for ename, edef in ont["edge_types"].items():
        via = edef.get("via", "-") or "-"
        lines.append(f"| `{ename}` | {edef['description']} | {edef['source']} | {edef['target']} | {via} |")
    lines.append("")

    # Metrics
    lines.append("## Metrics")
    lines.append("")
    lines.append("| ID | Description | Unit | Aggregation |")
    lines.append("|----|-------------|------|-------------|")
    for mid, mdef in ont["metrics"].items():
        lines.append(f"| `{mid}` | {mdef['description']} | {mdef['unit']} | {mdef['aggregation']} |")
    lines.append("")

    # Trait Definitions
    lines.append("## Trait Definitions")
    lines.append("")
    lines.append("| Name | Type | Description | Used By | Values |")
    lines.append("|------|------|-------------|---------|--------|")
    for tname, tdef in ont["trait_definitions"].items():
        used_by = ", ".join(tdef.get("used_by", []))
        values = ", ".join(tdef.get("values", [])) if tdef["type"] == "enum" else "-"
        lines.append(f"| `{tname}` | {tdef['type']} | {tdef['description']} | {used_by} | {values} |")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _write_or_check(path: Path, content: str, *, check: bool) -> bool:
    """Write *content* to *path*, or check if it matches.

    Returns True if the file is up-to-date (or was written successfully).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if check:
        if not path.exists():
            print(f"MISSING: {path}")
            return False
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            print(f"OK: {path}")
            return True
        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            content.splitlines(keepends=True),
            fromfile=str(path) + " (current)",
            tofile=str(path) + " (expected)",
        )
        sys.stdout.writelines(diff)
        print(f"MISMATCH: {path}")
        return False
    else:
        path.write_text(content, encoding="utf-8")
        print(f"GENERATED: {path}")
        return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate code from ontology.yaml")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that generated files are up-to-date without writing.",
    )
    args = parser.parse_args()

    ont = load_ontology()

    types_src = _generate_types(ont)
    validators_src = _generate_validators(ont)
    docs_src = _generate_docs(ont)

    results = [
        _write_or_check(TYPES_PATH, types_src, check=args.check),
        _write_or_check(VALIDATORS_PATH, validators_src, check=args.check),
        _write_or_check(DOCS_PATH, docs_src, check=args.check),
    ]

    if not all(results):
        sys.exit(1)


if __name__ == "__main__":
    main()
